### ISSUE TITLE
翻译质量

### ISSUE THREAD

**Issue by hangyan** [widuu/chinese_docker#32]
看了一篇，感觉翻译质量非常不好.
比如使用docker第一步“控制容器”这一篇.

# 开始一个新的容器
$ JOB=$(sudo docker run -d ubuntu /bin/sh -c "while true; do echo Hello world; sleep 1; done")
（**开始应改为创建为好，创建的是一个容器,变量名建议为CONTAINER**)

# 停止容器
$ docker stop $JOB

# 开始容器
$ docker start $JOB
(**启动容器**)

# 重启容器
$ docker restart $JOB

# 杀死一个工作
$ docker kill $JOB
(**工作应改为“任务”,更准确的应该是容器。另外，docker kill 和docker stop二者功能类似但有差别，应在此简要说明二者区别所在，不致引起初学者混淆**)

# 删除一个容器
$ docker stop $JOB # Container must be stopped to remove it
$ docker rm $JOB
(**docker删除容易不一定非要先停止容器**)

**Comment by widuu** [comment]
现在开始重新翻译和校正，感谢大家的关注，commit前边标识 complete的为已经翻译完成
