### ISSUE TITLE
你这个怎么参与翻译？

### ISSUE THREAD

**Issue by jiajunhuang** [widuu/chinese_docker#38]
没有事先约定各自翻译哪一篇， 容易碰一起吧？
而且应该怎么找哪些需要翻译呢？和docker.com比对哪些已经翻译哪些没有翻译吗？
而且应该把要翻译的英文放在这里面比较好， 翻译完了就可以删除

**Comment by zhuzhengguang** [comment]
good idea

**Comment by alwayslater** [comment]
好啊，中文文档的更新很慢啊，大家约一下

**Comment by alwayslater** [comment]
好啊，中文文档的更新很慢啊，大家约一下

**Comment by alwayslater** [comment]
好啊，中文文档的更新很慢啊，大家约一下

**Comment by widuu** [comment]
不好意思，这么晚才回复大家，这些日子一直在做别的开源产品！关于这个我建议大家这样：

Contributing

登录 https://github.com
Fork https://github.com/widuu/chinese_docker
创建您的特性分支 (git checkout -b my-new-feature)
提交您的改动 (git commit -am 'Added some feature')
将您的改动记录提交到远程 git 仓库 (git push origin my-new-feature)
然后到 github 网站的该 git 远程仓库的 my-new-feature 分支下发起 Pull Request

**Comment by liudonghua123** [comment]
还是没说清楚怎么协作，可能有的人同事对一篇文档都进行的翻译
可以在issue中提出那章节没有翻译，以章为单位进行翻译之后再pull request吧
