### ISSUE TITLE
翻译中不妥的地方

### ISSUE THREAD

**Issue by xishuixixia** [widuu/chinese_docker#5]
Hi，您好，我是InfoQ的中文编辑郭蕾，非常感谢你翻译的Docker中文指南。在阅读中我发现有很多地方有错别字，还希望能多检查，既然翻译了，就力争做到最好。完美是一种态度。

**Comment by widuu** [comment]
不好意思这么晚才回复你，去年时间短，没有注重这些，今年重新开启，我们将重新翻译1.5版本的Docker文档，现在前边表示complete的是已经翻译完成，准备校对的。我们会每天抽一点时间来翻译。谢谢您的关注，
