### ISSUE TITLE
window 下执行"hello world"命令与手册不同

### ISSUE THREAD

**Issue by yaowang908** [widuu/chinese_docker#55]
新手学习中，
安装好环境后，执行"docker run ubuntu:14.04 /bin/echo 'Hello World' "
会返回FATA[0005]…… c:/Program Files (x86)/Git/bin/echo: no such file or directory
但是执行" docker run ubuntu:14.04 echo 'hello world' "
会正常输出" hello world "
开始读官网的英文版的时候就发现这个问题，不知道什么原因，想请教一下。
是因为windows环境不一样吗，还是没有配置对呢

**Comment by widuu** [comment]
应该是你环境的问题，你这就直接调用到c:/Program Files (x86)/Git/bin/echo这个环境变量去了

**Comment by yaowang908** [comment]
多谢
