### ISSUE TITLE
Which docker hub repository use?

### ISSUE THREAD

**Issue by krahser** [widuu/chinese_docker#68]
Hello,

I'm having troubles to download images from the official repository.
Are you using some specific chinese repo?

Thank you very much

**Comment by twang2218** [comment]
It depends where you are. If you are currently in China, and having difficulty accessing Docker Hub, you can use several docker hub mirror sites, which is called '加速器' in China. Here is how to use it (in Chinese): https://blog.lab99.org/post/docker-2016-07-14-faq.html#docker-pull-hao-man-a-zen-me-ban

**Comment by krahser** [comment]
Thank you!
