### ISSUE TITLE
Error: i686 is not a recognized platform.

### ISSUE THREAD

**Issue by bfbd888** [widuu/chinese_docker#69]
root@ubuntu:~# wget -qO- https://get.docker.com/ | sh
Error: i686 is not a recognized platform.

**Comment by widuu** [comment]
Docker 不支持32位平台

**Comment by widuu** [comment]
32的ubuntu可以安装docker，但是pull下来的镜像必须是32位的。

https://registry.hub.docker.com/repos/32bit/
https://github.com/docker-32bit

**Comment by bfbd888** [comment]
多谢，解决了。
apt-get install docker.io
docker pull 32bit/ubuntu:16.04

**Comment by twang2218** [comment]
Ubuntu 系统源的 docker.io 不是当前的 Docker 版本。很多基本功能都不支持。你应该使用64位系统，并安装 Docker 官方源的 docker。

**Comment by bfbd888** [comment]
目前没看出docker.io和docker-engine有多大区别，够用了就没再折腾。

**Comment by twang2218** [comment]
区别很大，主要是版本，docker.io 的版本很老，而Docker 是只保证2-3个小版本内的兼容性。docker.io 对于 Ubuntu 14.04 而言是1.6，对于 16.04 而言是 1.10，都已经过时不再支持了，很多网络功能、服务发现、镜像检验、集群调度相关的东西都不支持。Docker 当前版本是 1.13，将来发布更加频繁，因此不推荐使用 docker.io 这个系统源中的包。

**Comment by bfbd888** [comment]
多谢多谢，查了一下，虽然集群功能不需要，但貌似新版本修改了很多Bug，的确要升级一下。
